/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:f1b0dcff-b218-4638-b36a-ed19b7c73578",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_5X4hg8mcO",
    "aws_user_pools_web_client_id": "2897874vmmmj7eig8hgasqo09m",
    "oauth": {}
};


export default awsmobile;
